version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.1
  clojure: lambdaisland/clojure@0.0.2

jobs:
  test:                                                                               
    parameters:                                                                       
      os:
        type: executor               
      clojure_version:                     
        type: string
    executor: << parameters.os >>    
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - run: npm install ws
            - kaocha/execute:
                aliases: :dev:test
                args: "--reporter documentation --plugin cloverage --codecov"
                clojure_version: << parameters.clojure_version >>
      - kaocha/upload_codecov

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              os: [clojure/openjdk15, clojure/openjdk11, clojure/openjdk8]
              clojure_version: ["1.10.2"]
